### ISSUE TITLE
-V / --version, about screen

### ISSUE THREAD

**Issue by pevik** [gfxprim/gppdf#4]
Although these tools are minimal, it'd be worth to have way to print version and also have some about screen with homepage.

**Comment by metan-ucw** [comment]
I guess that this may be something that should be added to each gfxprim application, I will think of something.

**Comment by metan-ucw** [comment]
Implemented in https://github.com/gfxprim/gfxprim/commit/a4b2b88eca01c988dcb8fa5376031f6b110edb1e

**Comment by pevik** [comment]
+1, haven't compiled, but sources looks well.
